authorization/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include
from . import views

app_name = 'authorization'

urlpatterns = [
        url(r'',views.check,name='check'),
]

council/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include
from . import views

app_name = 'council'

urlpatterns = [
        url(r'^$', views.HomeView.as_view(), name='home'),
        url(r'admin_page/',views.admin_page, name='admin_page'),
        url(r'clubCreate/',views.ClubCreateView.as_view(),name='club_create'),
        url(r'transactionCreate/',views.TransactionCreateView.as_view(),name='transaction_create'),
        url(r'meetCreate/',views.MeetCreateView.as_view(),name='meet_create'),
        url(r'getData/',views.get_data, name='get_data'),
]

council_website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from . import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url('^admin/', admin.site.urls),
    url(r'^account/', include('registration.urls')),
    url(r'^', include('council.urls'), name='council_main'),
    url(r'^grievance/', include('grievance.urls')),

]+ static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

grievance/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from . import views

app_name = 'grievance'

urlpatterns = [

    # url('^admin/', admin.site.urls),
    url(r'^posts/$',views.PostListView.as_view(),name='post_list'),
    url(r'^addcomment/(?P<post_id>\d+)/$',views.add_comment_view,name='add_comment'),
    url(r'^adminreply/(?P<pk>\d+)/$',views.admin_reply_comment, name='reply_admin'),
    url(r'^add_upvotes/(?P<post_id>\d+)/$',views.add_upvotes, name='add_upvotes'),
    url(r'^addgrievance/$',views.PostCreateView.as_view(), name='add_post'),



]

registration/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from . import views

# app_name = 'registration'

urlpatterns = [
    url(r'^', include('allauth.urls')),
]

council/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.urls import reverse
# Create your models here.
User = get_user_model()

class Club(models.Model):
    name = models.CharField(max_length=256)
    convenor = models.CharField(max_length=256)
    no_of_members = models.IntegerField()

    def __str__(self):
        return self.name


class Transaction(models.Model):
    reason = models.CharField(max_length=256)
    from_club = models.ForeignKey(Club,on_delete=models.CASCADE,related_name='from_club')
    to_club = models.ForeignKey(Club, on_delete=models.CASCADE,related_name='to_club')
    amount = models.FloatField()
    time = models.DateTimeField(editable=False)

    def save(self, *args,**kwargs):
        if not self.id:
            self.time = timezone.now()

        return super(Transaction,self).save(*args,**kwargs)

class Meet(models.Model):
    name = models.CharField(max_length=256)
    summary = models.TextField()
    detail  = models.TextField()
    time    = models.DateTimeField()

    def save(self, *args,**kwargs):
        if not self.id:
            self.time = timezone.now()

        return super(Meet,self).save(*args,**kwargs)

council/forms.py
# from django.contrib.auth.forms import UserCreationForm
# from .models import Users
#
# class UserForm(UserCreationForm):
#
#     class Meta(UserCreationForm.Meta) :
#         model = Users
#         fields = ['first_name', 'last_name', 'roll', 'username', 'is_member',
#                   'year', 'branch', 'section']

from django.contrib.auth import get_user_model
from .models import Club,Transaction,Meet
from django import forms

# class SignupForm(forms.ModelForm):
#     # first_name = forms.CharField(max_length=30, label='First Name', required = True)
#     # last_name = forms.CharField(max_length=30, label='Last Name', required=True)
#
#     class Meta:
#         model = Users
#         fields = ['first_name', 'last_name', 'roll', 'year', 'branch', 'section']
#
#     def signup(self, request, user):
#         user.first_name = self.cleaned_data['first_name']
#         user.last_name = self.cleaned_data['last_name']
#         user.roll = self.cleaned_data['roll']
#         user.year = self.cleaned_data['year']
#         user.section = self.cleaned_data['section']
#         user.branch = self.cleaned_data['branch']
#         user.save()


class ClubCreateForm(forms.ModelForm):

    class Meta:
        model = Club
        fields = ['name', 'convenor', 'no_of_members']


class TransactionCreateForm(forms.ModelForm):

    class Meta:
        model = Transaction
        fields = ['reason','from_club', 'to_club', 'amount']

class MeetCreateForm(forms.ModelForm):

    class Meta:
        model = Meet
        fields = ['name','summary','detail']

council/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView,TemplateView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from .forms import *
from .models import *
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required,permission_required
from django.contrib.auth.models import Permission

import json

User = get_user_model()

class HomeView(TemplateView):
    template_name = "council/index.html"

    # def get_context_data(self, **kwargs):
    #     context = super(HomeView, self).get_context_data(**kwargs)
    #     context['user'] = User.objects.all()
    #     return context

class ClubCreateView(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    permission_required = 'council.add_club'
    form_class = ClubCreateForm
    template_name = 'council/club_create.html'
    model = Club
    success_url = reverse_lazy('council:check')

class TransactionCreateView(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    permission_required = 'council.add_transaction'
    form_class = TransactionCreateForm
    template_name = 'council/transaction_create.html'
    model = Transaction
    success_url = reverse_lazy('council:check')

class MeetCreateView(LoginRequiredMixin,PermissionRequiredMixin, CreateView):
    permission_required = 'council.add_meet'
    form_class = MeetCreateForm
    template_name = 'council/meet_create.html'
    model = Meet
    success_url = reverse_lazy('council:check')


@login_required
def admin_page(request):
    transactions = Transaction.objects.all().order_by('-time')
    clubs = Club.objects.all()
    meets = Meet.objects.all().order_by('-time')
    total_clubs = len(clubs)
    total_transactions = len(transactions)
    total_meets = len(meets)
    context = {
        'clubs' : clubs,
        'transactions' : transactions,
        'meets'        : meets,
        'total_clubs' : total_clubs,
        'total_transactions': total_transactions,
        'total_meets' : total_meets
    }
    return render(request, 'council/admin2.html', context)


def get_data(request):
    transactions = Transaction.objects.all()
    return json.dump({'transactions' : transactions})

council/templates/council/admin.html
{% extends 'council/base.html' %}

{% block body %}

<style>

    #myFooter {
    background-color: #3c3d41;
    color: white;
    padding-top: 30px;
    bottom :0;
    position:absolute;
    right:0;
    left:0;
}
#myFooter .footer-copyright {
    background-color: #333333;
    padding-top: 3px;
    padding-bottom: 3px;
    text-align: center;
}
#myFooter .row {
    margin-bottom: 0px;
}
#myFooter .navbar-brand {
    margin-top: 45px;
    height: 65px;
}
#myFooter .footer-copyright p {
    margin: 10px;
    color: #ccc;
}
#myFooter ul {
    list-style-type: none;
    padding-left: 0;
    line-height: 1.7;
}
#myFooter h5 {
    font-size: 18px;
    color: white;
    font-weight: bold;
    margin-top: 30px;
}
#myFooter h2 a{
    font-size: 50px;
    text-align: center;
    color: #fff;
}
#myFooter a {
    color: #d2d1d1;
    text-decoration: none;
}
#myFooter a:hover,
#myFooter a:focus {
    text-decoration: none;
    color: white;
}
#myFooter .social-networks {
    text-align: center;
    padding-top: 30px;
    padding-bottom: 16px;
}
#myFooter .social-networks a {
    font-size: 32px;
    color: #f9f9f9;
    padding: 10px;
    transition: 0.2s;
}
#myFooter .social-networks a:hover {
    text-decoration: none;
}
#myFooter .facebook:hover {
    color: #0077e2;
}
#myFooter .google:hover {
    color: #ef1a1a;
}
#myFooter .instagram:hover {
    color: #ef1a10;
}
#myFooter .btn {
    color: white;
    background-color: #d84b6b;
    border-radius: 20px;
    border: none;
    width: 150px;
    display: block;
    margin: 0 auto;
    margin-top: 10px;
    line-height: 25px;
}
@media screen and (max-width: 767px) {
    #myFooter {
        text-align: center;
    }
}


</style>

{#<button type="button" class="btn btn-outline-secondary float-right"#}
{#        style="margin: 10px;padding: 20px;" data-toggle="modal" data-target="#ModalCenter">Add member</button>#}

<a href = "{% url 'account_signup' %}"><button type="button" class="btn btn-outline-secondary float-right"
        style="margin: 10px;padding: 20px;" >Add member</button></a>


<!-- Modal -->
<div class="modal fade" id="ModalCenter" tabindex="-1" role="dialog" aria-labelledby="ModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <form method="post" style="font-size: 25px;">
              {% csrf_token %}
              {% for field in form %}
                  <p>
                {{ field.label_tag }} {{ field }}
                  </p><br>
              {% endfor %}
          </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

<div class="container">
    <div class="row" style="">

<div class="card" style="width: 18rem;margin:8px">
  <div class="card-body">
    <h5 class="card-title">Meet 1</h5>
    <h6 class="card-subtitle mb-2 text-muted">Conducted on 04-10-2018</h6>
    <p class="card-text">Contains all the description of the meet</p>
      <ul class="">
          <li>Description through points</li>
      </ul>
    <a href="#" class="card-link">Website</a>
    <a href="#" class="card-link">Download</a>
  </div>
</div>

    <div class="card" style="width: 18rem;margin:8px">
  <div class="card-body">
    <h5 class="card-title">Meet 2</h5>
    <h6 class="card-subtitle mb-2 text-muted">Conducted on 05-10-2018</h6>
    <p class="card-text">Contains all the description of the meet</p>
      <ul class="">
          <li>Description through points</li>
      </ul>
    <a href="#" class="card-link">Website</a>
    <a href="#" class="card-link">Download</a>
  </div>
</div>

        <div class="card" style="width: 18rem;margin:8px">
  <div class="card-body">
    <h5 class="card-title">Meet 3</h5>
    <h6 class="card-subtitle mb-2 text-muted">Conducted on 06-10-2018</h6>
    <p class="card-text">Contains all the description of the meet</p>
      <ul class="">
          <li>Description through points</li>
      </ul>
    <a href="#" class="card-link">Website</a>
    <a href="#" class="card-link">Download</a>
  </div>
</div>
    </div>
</div>

<footer id="myFooter">

        <div class="container">

            <div class="row">

                <div class="col-sm-3">

                    <h2 class="logo"><a href="#" style="font-size:larger;">Students' Council</a></h2>

                </div>

                 <div class="col-sm-2">

                    <h5>Get started</h5>

                    <ul>
                        <li><a href="#">Home</a></li>
                        <!--<li><a href="#">Sign up</a></li>-->
                    </ul>

                </div>

                <div class="col-sm-2">

                    <h5>About us</h5>

                    <ul>
                        <!--<li><a href="#">Company Information</a></li>-->


                        <li>   <a href="mailto:sohampatil798@gmail.com" rel="nofollow">Mail Us </a></li>
                        <!--<li><a href="secondpages/Team.html">Visit Team</a></li>-->
                    </ul>

                </div>

                <div class="col-sm-2">

                    <h5>Support</h5>

                    <ul>
                        <li><a href="secondpages/Enquiry_page.html">Send Enquiry</a></li>
                        <li><a href="secondpages/Contact Us page.html">Contact Us</a></li>
                        <li><a href="#">Forums</a></li>
                    </ul>

                </div>

                <div class="col-sm-3">

                    <div class="social-networks">

                        <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
                        <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                        <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
                    </div>

                    <button type="button" class="btn btn-default">Review Us</button>

                </div>

            </div>
        </div>

        <div class="footer-copyright">

            <p>All rights reserved </p>

        </div>

    </footer>

{% endblock %}

council/templates/council/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    <!-- Bootstrap CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <title>Council</title>

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'authorization:check' %}" >Students' Council</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'council:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>

      <!--<li class="nav-item dropdown">-->
        <!--<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
          <!--Dropdown-->
        <!--</a>-->
        <!--<div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
          <!--<a class="dropdown-item" href="#">Action</a>-->
          <!--<a class="dropdown-item" href="#">Another action</a>-->
          <!--<div class="dropdown-divider"></div>-->
          <!--<a class="dropdown-item" href="#">Something else here</a>-->
        <!--</div>-->
      <!--</li>-->

    </ul>
{#    <form class="form-inline my-2 my-lg-0">#}
{#      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">#}
{#      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>#}
{#    </form>#}
  </div>
</nav>

{% block body %}
{% endblock %}
{#<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>#}
{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>#}
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script></body>
</html>

council/templates/council/club_create.html
{% extends 'council/base.html' %}

{% block body %}
    <div class="container border" style="margin: auto;margin-top: 50px;background: #f7f7f7; padding: 100px;">

        <form class=""  method="post" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.as_p }}

            <button type="submit" class="btn btn-primary btn-lg" name="button">Save</button>
    </form>

    </div>



{% endblock %}

council/templates/council/index.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Students' Council</title>

    {% load static %}
    {% load staticfiles %}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,60,700,800' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>

    <!-- Plugin CSS -->
    <link href="{% static 'vendor/magnific-popup/magnific-popup.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/creative.min.css' %}" rel="stylesheet">

  </head>

  <body id="page-top">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand js-scroll-trigger" href="{% if request.user.is_authenticated %}{% url 'authorization:check' %}{% else %}#page-top{% endif %}">Students' Council</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">


            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#about">About</a>
            </li>
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#services">Services</a>
          </li>
          <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#portfolio">Works</a>
          </li>


          <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="#contact">Contact</a>
          </li>

              {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" href="{% url 'grievance:post_list' %}">Redressal Forum</a>
            </li>
            
            <li class="nav-item">
              <a class="nav-link " href="{% url 'account_logout' %}">Logout</a>
            </li>
              {% else %}

            <li class="nav-item">
              <a class="nav-link " href="{% url 'account_signup' %}">Signup</a>
            </li>
            <li class="nav-item">
              <a class="nav-link " href="{% url 'account_login' %}">Login</a>
            </li>

            {% endif %}

          </ul>
        </div>
      </div>
    </nav>

    <header class="masthead text-center text-white d-flex">
      <div class="container my-auto">
        <div class="row">
          <div class="col-lg-10 mx-auto">
            <h1 class="text-uppercase">
              <strong>Your Representatives at Your Service</strong>
            </h1>
            <hr>
          </div>
          <div class="col-lg-8 mx-auto">
            <p class="text-faded mb-5">Council strives to work as an effective medium between Students and College Administration. Our goals always aim for the improvement in welfare and smooth running of various proceedings. </p>
            <a class="btn btn-primary btn-xl js-scroll-trigger" href="#about">Find Out More</a>
          </div>
        </div>
      </div>
    </header>

    <section class="bg-primary" id="about">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading text-white">We are here to help you!</h2>
            <hr class="light my-4">
            <p class="text-faded mb-4">All our members are always ready to uphold your requests on all management related queries. We aim at conducting programmes that help students get maximum benefit of college resources. All our proceedings are transparent and decisions are taken based on majority</p>
            <a class="btn btn-light btn-xl js-scroll-trigger" href="#services">Our Services!</a>
          </div>
        </div>
      </div>
    </section>

    <section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading">At Your Service</h2>
            <hr class="my-4">
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-gem text-primary mb-3 sr-icon-1"></i>
              <h3 class="mb-3">Sturdy Team</h3>
              <p class="text-muted mb-0">Best team of the college listening to you.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-paper-plane text-primary mb-3 sr-icon-2"></i>
              <h3 class="mb-3">Improvement</h3>
              <p class="text-muted mb-0">We try to bring improvements on all possible sectors.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-code text-primary mb-3 sr-icon-3"></i>
              <h3 class="mb-3">Up to Date</h3>
              <p class="text-muted mb-0">We make sure that all the works promised happen on time.</p>
            </div>
          </div>
          <div class="col-lg-3 col-md-6 text-center">
            <div class="service-box mt-5 mx-auto">
              <i class="fas fa-4x fa-heart text-primary mb-3 sr-icon-4"></i>
              <h3 class="mb-3">Co-operation</h3>
              <p class="text-muted mb-0">We try to extend maximum co-operation from our side.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="p-0" id="portfolio">
      <div class="container-fluid p-0">
        <div class="row no-gutters popup-gallery">
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/1.jpg' %}">
              <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/1.jpg' %}" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Infrastructure
                  </div>
                  <div class="project-name">
                    New Stationary Shop
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/2.jpg' %}">
              <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/2.jpg' %}" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Management
                  </div>
                  <div class="project-name">
                    New Admin Block
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/3.jpg' %}">
              <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/3.jpg' %}" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Clubs
                  </div>
                  <div class="project-name">
                    New Club for Photography
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/4.jpg' %}">
              <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/4.jpg' %}" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Events
                  </div>
                  <div class="project-name">
                      Cooking Competition Hosting
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/5.jpg' %}">
              <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/5.jpg' %}" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Installation
                  </div>
                  <div class="project-name">
                    New Training Block
                  </div>
                </div>
              </div>
            </a>
          </div>
          <div class="col-lg-4 col-sm-6">
            <a class="portfolio-box" href="{% static 'img/portfolio/fullsize/6.jpg' %}">
              <img class="img-fluid" src="{% static 'img/portfolio/thumbnails/6.jpg' %}" alt="">
              <div class="portfolio-box-caption">
                <div class="portfolio-box-caption-content">
                  <div class="project-category text-faded">
                    Workshop
                  </div>
                  <div class="project-name">
                    New Mechanical Workshop
                  </div>
                </div>
              </div>
            </a>
          </div>
        </div>
      </div>
    </section>

    <section class="bg-dark text-white" id="contact">
      <div class="container text-center">
        <h2 class="mb-4">Contact us if any queries!</h2>
        <a class="btn btn-light btn-xl sr-button" href="#final">Contact us!</a>
      </div>
    </section>

    <section id="final">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <h2 class="section-heading">Let's Get In Touch!</h2>
            <hr class="my-4">
            <p class="mb-5">Ready to work with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!</p>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-4 ml-auto text-center">
            <i class="fas fa-phone fa-3x mb-3 sr-contact-1"></i>
            <p>123-456-6789</p>
          </div>
          <div class="col-lg-4 mr-auto text-center">
            <i class="fas fa-envelope fa-3x mb-3 sr-contact-2"></i>
            <p>
              <a href="mailto:your-email@your-domain.com">feedback@studentscouncil.com</a>
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
    <script src="{% static 'vendor/scrollreveal/scrollreveal.min.js' %}"></script>
    <script src="{% static 'vendor/magnific-popup/jquery.magnific-popup.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'js/creative.min.js' %}"></script>

  </body>

</html>

council/templates/council/meet_create.html
{% extends 'council/base.html' %}

{% block body %}
    <div class="container border" style="margin: auto;margin-top: 50px;background: #f7f7f7; padding: 100px;">

        <form class=""  method="post" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.as_p }}

            <button type="submit" class="btn btn-primary btn-lg" name="button">Save</button>
    </form>

    </div>



{% endblock %}

council/templates/council/transaction_create.html
{% extends 'council/base.html' %}

{% block body %}
    <div class="container border" style="margin: auto;margin-top: 50px;background: #f7f7f7; padding: 100px;">

        <form class=""  method="post" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.as_p }}

            <button type="submit" class="btn btn-primary btn-lg" name="button">Save</button>
    </form>

    </div>



{% endblock %}