council/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.urls import path,include
from . import views

app_name = 'council'

urlpatterns = [
        url(r'^$', views.HomeView.as_view(), name='home'),
        url(r'admin_page/',views.admin_page, name='admin_page'),
        url(r'clubCreate/',views.ClubCreateView.as_view(),name='club_create'),
        url(r'transactionCreate/',views.TransactionCreateView.as_view(),name='transaction_create'),
        url(r'meetCreate/',views.MeetCreateView.as_view(),name='meet_create'),
        url(r'getData/',views.get_data, name='get_data'),
]

council_website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from . import views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    url('^admin/', admin.site.urls),
    url(r'^account/', include('registration.urls')),
    url(r'^', include('council.urls'), name='council_main'),
    url(r'^grievance/', include('grievance.urls')),

]+ static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

grievance/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from . import views

app_name = 'grievance'

urlpatterns = [

    # url('^admin/', admin.site.urls),
    url(r'^posts/$',views.PostListView.as_view(),name='post_list'),
    url(r'^addcomment/(?P<post_id>\d+)/$',views.add_comment_view,name='add_comment'),
    url(r'^adminreply/(?P<pk>\d+)/$',views.admin_reply_comment, name='reply_admin'),
    url(r'^add_upvotes/(?P<post_id>\d+)/$',views.add_upvotes, name='add_upvotes'),
    url(r'^addgrievance/$',views.PostCreateView.as_view(), name='add_post'),



]

registration/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url
from . import views

# app_name = 'registration'

urlpatterns = [
    url(r'^', include('allauth.urls')),
]

grievance/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.urls import reverse
# Create your models here.
User = get_user_model()

class Post(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)
    text = models.TextField()
    upvote = models.IntegerField(default=0)
    implemented = models.BooleanField(default=False)
    created_date = models.DateTimeField(default = timezone.now)
    published_date = models.DateTimeField( blank=True, null = True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def get_absolute_url(self):
        return reverse("grievance:post_list")

    def __str__(self):
        return self.title

class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete = models.CASCADE)
    parent_comment = models.ForeignKey("self", related_name='parent', on_delete = models.CASCADE, null=True, blank =True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)


    def get_absolute_url(self):
        return reverse("post_list")

    def children(self): #replies
        return Comment.objects.filter(parent=self)

    def __str__(self):
        return self.text

class Event(models.Model):
    created_date = models.DateField()
    finished_date = models.DateField(null = True, blank = True)
    title = models.CharField(max_length = 50)
    text = models.CharField(max_length = 300)

    def __str_(self):
        return self.title

class TimePoint(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name='timepoints')
    date = models.DateField()
    text = models.CharField(max_length = 100)

    def __str__(self):
        return self.event.title

# class Secretary(models.Model):
#     status = models.ForeignKey(Comment, on_delete=models.CASCADE)

grievance/forms.py
from django import forms

from .models import Comment, Post

class CommentReplyForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

class AddPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','text','created_date','author')

grievance/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required, permission_required
from .models import Post, Event, Comment
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.contrib.auth.decorators import user_passes_test

from django.views.generic import (TemplateView,ListView,
                                  DetailView,CreateView,
                                  UpdateView,DeleteView)
from django.contrib.auth import get_user_model
from .forms import CommentReplyForm, AddPostForm

from django.http import HttpResponseRedirect

from django.urls import reverse
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
User = get_user_model()
# Create your views here.

class PostListView(LoginRequiredMixin,PermissionRequiredMixin,ListView):
    permission_required = 'grievance.view_post'
    model = Post
    context_object_name = 'posts'
    template_name = 'grievance/complaints/posts.html'

    def get_queryset(self):
        return Post.objects.all().order_by('-upvote')

    def get_context_data(self, **kwargs):
        context = super(PostListView, self).get_context_data(**kwargs)
        context['user'] = User.objects.filter(email=self.request.user.email)
        return context

# class AddCommentView(LoginRequiredMixin,CreateView):
#     model = Comment
#     form_class = CommentReplyForm
#     template_name = 'grievance/complaints/comment_reply_form.html'

class PostCreateView(LoginRequiredMixin,PermissionRequiredMixin,CreateView):
    permission_required = 'grievance.add_post'
    form_class = AddPostForm
    template_name = 'grievance/complaints/post_form.html'
    model = Post

    def get_initial(self):
        """
        Returns the initial data to use for forms on this view.
        """
        initial = super().get_initial()
        initial['author'] = self.request.user

        return initial

# class EventListView(ListView):
#     model = Event
#     context_object_name = 'events'
#     template_name = 'blog/events/events.html'

@login_required
@permission_required('grievance.add_comment')
def admin_reply_comment(request, pk):
    parent = get_object_or_404(Comment, pk=pk)
    post = parent.post
    if request.method == "POST":
        form = CommentReplyForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.parent_comment = parent
            comment.save()
            return redirect('grievance:post_list')
    else:
        form = CommentReplyForm()
    return render(request, 'grievance/complaints/comment_reply_form.html', {'form': form})

@permission_required('grievance.add_comment')
def add_comment_view(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == "POST":
        form = CommentReplyForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = post
            comment.save()
            return redirect('grievance:post_list')
    else:
        form = CommentReplyForm()
    return render(request, 'grievance/complaints/comment_reply_form.html', {'form': form})




@login_required
@permission_required('grievance.view_post')
def add_upvotes(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    post.upvote += 1
    post.save()

    return HttpResponseRedirect(reverse('grievance:post_list'))


    # def get_queryset(self):
    #     # super().get_queryset()
    #     return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

grievance/templates/grievance/complaints/comment_detail.html
<blockquote class="blockquote mb-0" style="margin-bottom:0px; margin-top:0px;">
  {% if request.user.is_admin %}
  <a href="{% url 'grievance:reply_admin' comment.pk %}" class="tooltipped" data-position="top" data-tooltip="Click to reply">{{comment.text}}</a>
  {% else %}
  <p>{{comment.text}}</p>
  {% endif %}
  <footer class="blockquote-footer"> <cite title="Source Title">- {{comment.author.first_name}} {{comment.author.last_name}}</cite></footer>
</blockquote>

<script type="text/javascript">
  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.tooltipped');
    var instances = M.Tooltip.init(elems, options);
  });
</script>

grievance/templates/grievance/complaints/comment_reply_form.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn waves-effect waves-light">Submit</button>
  </form>
</div>

{% endblock %}

grievance/templates/grievance/complaints/comments.html
<ul class="collection with-header">
  {% for comment in comments.all %}
  {% if comment.parent_comment == None and not comment.author.is_admin %}
    <li class="collection-item" style="margin:8px;">{% include "grievance/complaints/comment_detail.html" with comment=comment%}</li>
  {% endif %}

  {% empty %}
  <p>No comments yet!</p>
  {% endfor %}

  <a class="waves-effect waves-light btn-small" href="{% url 'grievance:add_comment' post.pk%}">Add Comment</a>
</ul>

grievance/templates/grievance/complaints/post_detail.html
<div class="card post-detail">



  <div class="card-content post-detail-content">
    <div>
      <span class="card-title">{{post.title}}</span>
      <div class="chip float right">
        Implemented
        {% if post.implemented %}
        <i class="material-icons right" style="font-size:20px; margin-top:5%;">check</i>
        {% else %}
        <i class="material-icons right" style="font-size:20px; margin-top:5%;">clear</i>
        {% endif %}
      </div>

    </div>
    <br>
    
    <p>{{post.text}}</p>
  </div>



  <div class="card-reveal">
      <span class="card-title grey-text text-darken-4" >Comments<i class="material-icons right" >close</i></span>
    <div class="reveal-html">
        {% include "grievance/complaints/comments.html" with comments=post.comments post=post %}
    </div>
  </div>


  <div class="card-tabs">
    <ul class="tabs tabs-fixed-width">
      <li class="tab"><a class="upvote com" href="{% url 'grievance:add_upvotes' post.pk %}">Upvote ({{post.upvote}})</a></li>
      <li class="tab"><a  class="comments activator com">Comments</a></li>
      <li class="tab"><a class="secretary modal-trigger com" href="#{{post.pk}}">Redressal</a></li>
    </ul>
  </div>

  <div id="{{post.pk}}" class="modal">
  <div class="modal-content">
    <h4>Council Members Say</h4>
    {% include "grievance/complaints/redressal.html" with comments=post.comments post=post %}
  </div>
  <div class="modal-footer">
    <a href="#!" class="modal-action modal-close waves-effect waves-green btn-flat">Okay!</a>
  </div>
</div>

  <script>
  $(document).ready(function(){
    $('.modal').modal();
  });
  </script>




</div>

grievance/templates/grievance/complaints/post_form.html
{% extends "base.html" %}

{% block content %}
<div class="container">
  <form method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn waves-effect waves-light">Submit Grievance</button>
  </form>
</div>

{% endblock %}

grievance/templates/grievance/complaints/posts.html
{% extends "base.html" %}


{% block content %}



<div class="container">
  <div class = "row" style="margin-top:5em;">
    <div class="col s6">
      <h2 style="margin:0px; float:left;">Suggestions</h2>
    </div>
    <div class="col s6">
      <a class="waves-effect waves-light btn-large" style="float:right;" href="{% url 'grievance:add_post' %}">Add Grievance</a>
    </div>
  </div>

  <div class="container suggestions-text">

  <div class="container">
    <h3 style="margin:2% 0 1% 5%;">What's this?</h3>
    <p class="text-usage">Students can drop their suggestions/complaints here, which shall regularly be addressed by the candidate.</p>
    <p class="text-usage">If a student happens to have a suggestion that's already posted, she may upvote it in order to increase its priority of redressal.</p>
    <p class="text-usage">The candidates opinion on a suggestion/ status of the work being done on it can be seen using 'Redressal'.</p>

  </div>

  </div>

   {% for post in posts %}
       {% include "grievance/complaints/post_detail.html" with post=post %}
   {% endfor %}
</div>

{% endblock %}

grievance/templates/grievance/complaints/redressal.html
{% for comment in comments.all %}


{%if comment.author.is_admin %}

{% if comment.parent_comment %}
<div class="card">
  <div class="card-content sec-card" style="padding:0px;">
    {% include "grievance/complaints/comment_detail.html" with comment=comment %}
  </div>
  <div class="card-content sec-card grey lighten-4" style="padding:0px;">
      <p style="font-style:italic;"> In response to</p>
      {% include "grievance/complaints/comment_detail.html" with comment=comment.parent_comment%}
  </div>
</div>


{% else%}

<div class="card">
  <div class="card-content sec-card" style="padding:0px;">
    {% include "grievance/complaints/comment_detail.html" with comment=comment %}
  </div>

</div>

{% endif %}

{% endif %}

{% empty %}
<h6>No redressal yet! Please check after some time!</h6>

{%endfor%}